const COUNTY_SUFFIX = " County";

export const SITE_CONFIG = {
  app: {
    name: "h1b-WageMap",
    subtitle:
      "2027–2028 prevailing wages. Select a state or county, occupation, and salary.",
  },
  share: {
    title: "h1b-WageMap",
    text: "Check 2027–2028 H-1B prevailing wage levels by U.S. county",
    copiedMessage: "Link copied to clipboard",
  },
  data: {
    countiesUrl: "/counties.geojson",
    socCodesUrl: "/data/soc_codes.json",
    socDataPath: "/data/soc",
    geoidsUrl: "/data/geoids.json",
    countySuffix: COUNTY_SUFFIX,
  },
  defaults: {
    soc: "15-1252",
    socText: "15-1252.00 – Software Developers",
    salary: 110000,
  },
  query: {
    keys: {
      state: "state",
      county: "county",
      soc: "soc",
      salary: "salary",
      h1b: "h1b",
    },
    truthyValues: ["1", "true", "yes", "on"],
  },
  wage: {
    hoursPerYear: 2080,
  },
  map: {
    styleUrl: "https://tiles.openfreemap.org/styles/positron",
    bounds: [
      [-125, 24],
      [-66, 50],
    ],
    fitBounds: {
      initPadding: 20,
      padding: 30,
      duration: 600,
    },
    popupOffset: 12,
    maxCountyZoom: 8,
    sources: {
      counties: "counties",
    },
    layers: {
      countyFill: "county-fill",
      countyNoData: "county-nodata",
      countyOutline: "county-outline",
    },
    paint: {
      countyFill: {
        color: "#F3F4F6",
        opacity: 0.8,
      },
      countyOutline: {
        color: "#94a3b8",
        width: 0.6,
        opacity: 0.55,
      },
      noDataFill: "#F3F4F6",
      belowLevelFill: "#B8BEC8",
      noLevelBadge: "#d1d5db",
    },
  },
  levels: {
    keys: ["I", "II", "III", "IV"],
    colors: {
      0: "#B8BEC8",
      1: "#7EC8E3",
      2: "#3D9B7A",
      3: "#C07AA8",
      4: "#3D5A80",
    },
    labels: {
      noData: "No data",
      belowLevel: "Below Level I",
      levelPrefix: "Level",
      legend: {
        0: "Below I",
        1: "Level I",
        2: "Level II",
        3: "Level III",
        4: "Level IV",
        noData: "No data",
      },
      tableHeaders: {
        level: "Level",
        salary: "Annual salary",
        probability: "Probability",
      },
      tableLevelPrefix: "L",
    },
  },
  lottery: {
    selectionByLevel: {
      1: 15.29,
      2: 30.58,
      3: 45.87,
      4: 61.16,
    },
    selectionLineTemplate:
      "You have a {{chance}}% estimated probability of being selected to file an H-1B petition in 2027–2028.",
    toggleQuestion:
      "Would you like to see estimated H-1B lottery chances for 2027–2028?",
    disclaimer:
      "DHS estimates for a wage-weighted lottery, not actual 2027–2028 selection rates.",
    toggleAriaLabel: "Toggle lottery selection chances",
    toggleOnLabel: "On",
    toggleOffLabel: "Off",
  },
  ui: {
    location: {
      label: "Location",
      hint: "Optional — zooms the map",
      allStates: "All states",
      selectCounty: "Select county",
      pickStateFirst: "Pick a state first",
      countySuffix: "",
    },
    occupation: {
      label: "Occupation",
      hint: "Type any part of a title or SOC",
      placeholder: "Software, 15-1252, nurse…",
      clearLabel: "Clear occupation",
      helpLabel: "Help",
      infoTitle: "Can’t find your job title?",
      infoParagraphs: [
        "Try searching using a broader or more common job title. Many roles are grouped under standard occupational categories.",
        "For example, search for Software Developer instead of Backend Engineer, or Operations Manager instead of Program Lead.",
        "Once selected, adjust the salary to see which wage level applies by county.",
        "to find more job titles and SOC codes.",
      ],
      infoLinkText: "O*NET (Occupational Keyword Search)",
    },
    salary: {
      label: "Annual Base Salary",
      hint: "Used to determine wage level",
      clearLabel: "Clear salary",
      inputPaddingRight: 28,
    },
    panel: {
      expandAriaLabel: "Expand panel",
      collapseAriaLabel: "Minimize panel",
      expandTitle: "Expand",
      collapseTitle: "Hide panel",
      minimizeButtonLabel: "Hide panel",
    },
    pinned: {
      occupation: "Occupation",
      salary: "Salary",
      title: "Current selection",
    },
    share: {
      ariaLabel: "Share",
      title: "Share",
    },
    legendTitle: "Prevailing wage level color scale",
  },
  links: {
    disclosures: "/disclosures.html",
    disclosuresLabel: "Disclosures ↗",
    oflc: "https://flag.dol.gov/wage-data/wage-search",
    oflcLabel: "OFLC Wage Data ↗",
    onet: "https://www.onetonline.org/find/result",
    authorName: "Pranay Mandadapu",
    authorUrl: "https://github.com/sunnypranay",
  },
  formatting: {
    locale: "en-US",
    emptyValue: "—",
    currencySymbol: "$",
    annualSuffix: "/yr",
    thousandsDivisor: 1000,
    thousandsSuffix: "K",
    socSeparator: " – ",
  },
  autocomplete: {
    wrapperStyle: {
      position: "relative",
      width: "100%",
      flex: 1,
      minWidth: 0,
    },
    inputPaddingRight: 28,
    menuStyle: {
      position: "absolute",
      zIndex: 10,
      background: "#fff",
      border: "1px solid #ccc",
      maxHeight: 200,
      overflowY: "auto",
      width: "100%",
      fontSize: 14,
    },
    optionStyle: {
      padding: "6px",
      cursor: "pointer",
      borderBottom: "1px solid #eee",
    },
  },
};

// STATEFP (Census) -> State Abbreviation
export const STATE_FP_TO_ABBR = {
  "01": "AL",
  "02": "AK",
  "04": "AZ",
  "05": "AR",
  "06": "CA",
  "08": "CO",
  "09": "CT",
  10: "DE",
  11: "DC",
  12: "FL",
  13: "GA",
  15: "HI",
  16: "ID",
  17: "IL",
  18: "IN",
  19: "IA",
  20: "KS",
  21: "KY",
  22: "LA",
  23: "ME",
  24: "MD",
  25: "MA",
  26: "MI",
  27: "MN",
  28: "MS",
  29: "MO",
  30: "MT",
  31: "NE",
  32: "NV",
  33: "NH",
  34: "NJ",
  35: "NM",
  36: "NY",
  37: "NC",
  38: "ND",
  39: "OH",
  40: "OK",
  41: "OR",
  42: "PA",
  44: "RI",
  45: "SC",
  46: "SD",
  47: "TN",
  48: "TX",
  49: "UT",
  50: "VT",
  51: "VA",
  53: "WA",
  54: "WV",
  55: "WI",
  56: "WY",
  72: "PR",
};

export const STATE_ABBR_TO_NAME = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DC: "District of Columbia",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  IA: "Iowa",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  MA: "Massachusetts",
  MD: "Maryland",
  ME: "Maine",
  MI: "Michigan",
  MN: "Minnesota",
  MO: "Missouri",
  MS: "Mississippi",
  MT: "Montana",
  NC: "North Carolina",
  ND: "North Dakota",
  NE: "Nebraska",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NV: "Nevada",
  NY: "New York",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VA: "Virginia",
  VT: "Vermont",
  WA: "Washington",
  WI: "Wisconsin",
  WV: "West Virginia",
  WY: "Wyoming",
};
